server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elasticsearch?serverTimezone=Asia/Seoul
    username: sbsst
    password: sbs123414
  jpa:
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true

elasticsearch:
  host: hyper-x.kr
  port: 9200

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE